### ISSUE TITLE
function composition resolving predicates in the wrong module

### ISSUE THREAD

**Issue by mndrix** [mndrix/func#11]
Inside a module foo, I had imported a predicate bar_stuff/2 from the module bar.  I composed the following function:

```
F = reverse of bar_stuff.
```

When applying `F` to a value, I got the error:

```
Undefined procedure: func:bar_stuff/2
```

The composed function was looking in the `func` module when it should have been looking in the `foo` module.

Make function composition look in the module in which the composed function was defined.

**Comment by logicmoo** [comment]
I seem to work around it at https://github.com/logicmoo/func

**Comment by mndrix** [comment]
@logicmoo can you write a test case and then submit your changes as a pull request?

**Comment by logicmoo** [comment]
Test via main of 

https://github.com/logicmoo/func/blob/master/t/test_func_11.pl
https://github.com/logicmoo/func/blob/master/t/test_func_11_compose.pl
