### ISSUE TITLE
Module qualified functions

### ISSUE THREAD

**Issue by edechter** [mndrix/func#16]
Currently functions are expanded without module qualification. 

```
:- use_module(library(func)).

foo :-
    length(mod:bar(~)).

:- initialization listing(foo/0). 
```

```
bash-3.2$ swipl -l test_func.pl
foo :-
	bar(A),
	length((mod):A).
```

**Comment by mndrix** [comment]
Fixed in v0.4.2

**Comment by edechter** [comment]
Why is this (in commit message 6607fcb) true?
`Having non-test files under t/ prevents us from running the entire test
suite with a single 'prove' command.` 

Can't we put the

**Comment by mndrix** [comment]
> Why is this true?

I run the test suite for my packs with a command like:

```
prove --ext=pl -j4 -r -e 'swipl -q -f dev.pl -t main -s' t/
```

So any `.pl` file under the t directory is considered a test.
